#!/bin/sh
# Regenerates Formula/weather-outlook.rb from the latest weather-outlook GitHub release.
set -eu
REPO="cport1/weather-outlook"
version="${1:-$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" | sed -n 's/.*"tag_name": *"v\{0,1\}\([^"]*\)".*/\1/p' | head -n1)}"
[ -n "$version" ] || { echo "no version" >&2; exit 1; }
base="https://github.com/$REPO/releases/download/v$version"
sums=$(curl -fsSL "$base/SHA256SUMS")
sha() { printf '%s\n' "$sums" | awk -v f="weather-outlook-$version-$1" '$2 == f { print $1 }'; }
for t in darwin-arm64 darwin-x64 linux-arm64 linux-x64; do
  [ -n "$(sha "$t")" ] || { echo "missing checksum for $t" >&2; exit 1; }
done
cat > Formula/weather-outlook.rb <<RUBY
# Generated by update-formula.sh — do not edit by hand.
class WeatherOutlook < Formula
  desc "Terminal weather dashboard: radar, hurricanes, wildfires, quakes and alerts"
  homepage "https://github.com/$REPO"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/weather-outlook-$version-darwin-arm64"
      sha256 "$(sha darwin-arm64)"
    end
    on_intel do
      url "$base/weather-outlook-$version-darwin-x64"
      sha256 "$(sha darwin-x64)"
    end
  end

  on_linux do
    on_arm do
      url "$base/weather-outlook-$version-linux-arm64"
      sha256 "$(sha linux-arm64)"
    end
    on_intel do
      url "$base/weather-outlook-$version-linux-x64"
      sha256 "$(sha linux-x64)"
    end
  end

  def install
    bin.install Dir["weather-outlook-*"].first => "weather-outlook"
    bin.install_symlink "weather-outlook" => "wo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/weather-outlook --version")
  end
end
RUBY
echo "weather-outlook $version"
