# Generated by update-formula.sh — do not edit by hand.
class WeatherOutlook < Formula
  desc "Terminal weather dashboard: radar, hurricanes, wildfires, quakes and alerts"
  homepage "https://github.com/cport1/weather-outlook"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cport1/weather-outlook/releases/download/v2.1.0/weather-outlook-2.1.0-darwin-arm64"
      sha256 "ad17c15e62856e2ac0d9aeadebb8e8dc55a9208aae97a867f257087ea210a3d1"
    end
    on_intel do
      url "https://github.com/cport1/weather-outlook/releases/download/v2.1.0/weather-outlook-2.1.0-darwin-x64"
      sha256 "d20df84fa5195df97ec7dcd70e698ae5b2be2e1d35e0b1c594fbd8162a066695"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cport1/weather-outlook/releases/download/v2.1.0/weather-outlook-2.1.0-linux-arm64"
      sha256 "9339b071b453bd9e31fee87d17472229b8493ab0158de0c26e3d869d8151ab81"
    end
    on_intel do
      url "https://github.com/cport1/weather-outlook/releases/download/v2.1.0/weather-outlook-2.1.0-linux-x64"
      sha256 "28b8991c6195f5f5a321d32b0dbcdfb049a6c84d8c9ec1077199199a68672eb5"
    end
  end

  def install
    bin.install Dir["weather-outlook-*"].first => "weather-outlook"
    bin.install_symlink "weather-outlook" => "wo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/weather-outlook --version")
  end
end
