# Generated by update-formula.sh — do not edit by hand.
class WeatherOutlook < Formula
  desc "Terminal weather dashboard: radar, hurricanes, wildfires, quakes and alerts"
  homepage "https://github.com/cport1/weather-outlook"
  version "2.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cport1/weather-outlook/releases/download/v2.0.0/weather-outlook-2.0.0-darwin-arm64"
      sha256 "c697d73b5c6185e9434d6709faba002831f7272004f79090fcaf39929bb62afc"
    end
    on_intel do
      url "https://github.com/cport1/weather-outlook/releases/download/v2.0.0/weather-outlook-2.0.0-darwin-x64"
      sha256 "22ea9537c6917d9e724259efebb2fa4e41b817a97da7180bec776d42c73653a6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cport1/weather-outlook/releases/download/v2.0.0/weather-outlook-2.0.0-linux-arm64"
      sha256 "8f7e2d1edaa29d0afbb6b24114715b92dda429897233b0c13832a78ccc0c6fbe"
    end
    on_intel do
      url "https://github.com/cport1/weather-outlook/releases/download/v2.0.0/weather-outlook-2.0.0-linux-x64"
      sha256 "3db49b5e8fdd6f56494b2b7f7fca6e932d65095bd578790bafbd34e0a478d023"
    end
  end

  def install
    bin.install Dir["weather-outlook-*"].first => "weather-outlook"
    bin.install_symlink "weather-outlook" => "wo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/weather-outlook --version")
  end
end
