# Generated by update-formula.sh — do not edit by hand.
class WeatherOutlook < Formula
  desc "Terminal weather dashboard: radar, hurricanes, wildfires, quakes and alerts"
  homepage "https://github.com/cport1/weather-outlook"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cport1/weather-outlook/releases/download/v2.1.1/weather-outlook-2.1.1-darwin-arm64"
      sha256 "451d139fc6b3f83c5687090b88a7a5cb527e43544b866ee203a38054a968a514"
    end
    on_intel do
      url "https://github.com/cport1/weather-outlook/releases/download/v2.1.1/weather-outlook-2.1.1-darwin-x64"
      sha256 "26ecbe6d0be64086ed9e4fabeef50f5a44830dbfbecc6296ad7a63be712f9b60"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cport1/weather-outlook/releases/download/v2.1.1/weather-outlook-2.1.1-linux-arm64"
      sha256 "05663f491ee33de15ba739637a2db016d2fbe7a85024b9aded09effd0ae69100"
    end
    on_intel do
      url "https://github.com/cport1/weather-outlook/releases/download/v2.1.1/weather-outlook-2.1.1-linux-x64"
      sha256 "1e5e3af3899f6b52c053041b2a275eb4e588005ef90f88c668c43bfce5bb7bc4"
    end
  end

  def install
    bin.install Dir["weather-outlook-*"].first => "weather-outlook"
    bin.install_symlink "weather-outlook" => "wo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/weather-outlook --version")
  end
end
